Add translations check with lupdate
trikset/trik-checkapp pull request #16
Opened 2021-08-02 04:36 UTC by khodand

2021-08-04 15:40 UTC, iakov requested changes
Точно всё готово?

2021-08-04 15:56 UTC, khodand commented
> 
> 
> Точно всё готово?

Нет, я забыл, хотел помощи попросить. Я не очень понимаю в чём дело. Как я понимаю это CRLF, но вроде должно быть отключено

2021-08-06 13:14 UTC, iakov commented
Да, надо настроить `core.autocrlf` на `auto` у тебя починить этот файл. В файле в гите должны быть только LF, а локально уже он разберётся. Можешь у себя (если на винде) поставить в `input` и файл обновить в индексе. 
Ещё полезно знать про https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresafecrlf , можно делать `warn` у себя локально.

2021-08-06 13:20 UTC, iakov commented
Подробнее, например, тут: https://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git

2021-11-04 11:57 UTC, iakov commented
Сдеалай, плиз, аккуратный `git rebase` на мастер

2021-12-16 12:28 UTC, iakov commented
Сделай, пожалуйста, ребейз на мастер.

2021-12-17 08:40 UTC, iakov approved these changes

2021-12-17 08:40 UTC, merged